### ISSUE TITLE
TODO just before releasing v0.3

### ISSUE THREAD

**Issue by JackKelly** [nilmtk/nilmtk#263]
- [ ] annotated git tag v0.3
- [ ] update version.py 
- [ ] update version in docs 
- [ ] create folders  on nilmtksite for the relevant documentation (v0.2, v0.3, devel) and change the destination directory for html files in the documentation conf.py file. See #196
- [ ] update install instructions
- [ ] add a bug submission guide

Publicising:
- [ ] write blog posts
- [ ] tweet on personal accounts and nilmtk account
- [ ] nilmtk mailing list 
- [ ] Google Plus 
- [ ] Google Hangout demo?

Please feel free to add other items to the list above.
